---
title: "Cycling Land's End to John O' Groats"
excerpt: "1 week and over 900 miles cycled. A record of the week and advice to others planning their own adventure"
header:
  teaser: "https://github.com/mikey-harper/mikey-harper.github.io/blob/master/_images/LEJOGStart.jpg?raw=true"
comments: true
categories: 
- Cycling
- Maps
toc: true
toc_label: "Table of Contents"
---


## Budget

We set out with a target to spend less than £500 for the trip (excluding any gear). Our overall budget came to £521, which we were happy with.

```{r, results="asis"}
library(googleVis)
op <- options(gvis.plot.tag='chart')
df=data.frame(country=c("US", "GB", "BR"), 
              val1=c(10,13,14), 
              val2=c(23,12,32))
Line <- gvisLineChart(df)
plot(Line)
```


The main ways we saved money were:

- Booking travel well in advance
- Buying food from supermarkets and cooking our own breakfasts and dinners. We also made our sandwiches for the day.
- Staying with family or hostels. This becomes more difficult in Scotland as there are fewer cheap options
- We spent slightly more in accommodation in Scotland than we intended to, but this was partly due to the limited availability.

## Lessons Learnt

One of the issues with planning our routes using Strava is that they were not always necessarily that easy to follow. They would often wind down side lanes with lots of turns. It was therefore essential that we loaded the routes onto our bike GPS so that we could follow the directions as we went.

Another big challenge is timekeeping. It is easy to set off slightly late each day, have an extra few breaks or stop slightly too long for lunch. We often found ourselves overrunning our planned time and meant cycling into the evening.

We didn’t plan our intermediate stops each day, and just relied on finding a big enough town or village to stock up on food and drink. While this worked out for most of the trip, there were a few occasions where we were caught out and had very little food or water for a couple of hours.
