---
title: 'Writing reports in RStudio: an introduction to RMarkdown'
description: Learn why you should consider the benefits of RMarkdown for doing data-driven research. This post shares a presentation which I gave to the Spatial Modelling group, and provides some useful resources for futher reading. 
author: Mikey Harper
date: '2017-10-02'
slug: writing-reports-in-rstudio-an-introduction-to-rmarkdown
categories: []
tags:
  - R
  - Presentation
  - Reproducible Resaerch
type: post

topics:
  - Technical
---

RMarkdown is a powerful tool for producing documents with embedded R code, allowing you to easily reproduce analysis and greatly simplify your data-driven workflow. It can be used to generate dynamic reports, presentations, journal papers, and even your thesis!

The presentation was designed to provide a whistle-stop tour of the benefits of RMarkdown, explaining the basic syntax to get started and highlighting some of the more advance things which you could use RMarkdown for.

<script async class="speakerdeck-embed" data-id="4762f43cec7a4a75be0c23f06526dac2" data-ratio="1.33333333333333" src="//speakerdeck.com/assets/embed.js"></script>

[Download Presentation (PDF)](https://speakerd.s3.amazonaws.com/presentations/4762f43cec7a4a75be0c23f06526dac2/Writing_reports_in_RStudio.pdf){: .btn .btn--primary}

## Useful Links

Reading is essential to gain a full understanding of RMarkdown. The following links are recommended within the presentation.

**RMarkdown Detailed Guidance**

- **[RMarkdown Website](http://rmarkdown.rstudio.com/index.html):** Essential reading: used for much of the content of this presentation
- **[Knitr Code Chunk Options](https://yihui.name/knitr/options/)**: the full list of commands which can be used to control code output for the chunks
- **[YAML PDF Settings](http://rmarkdown.rstudio.com/pdf_document_format.html)**: a full list of commands which can be used to control the output of PDF documents (LaTeX) within RMarkdown.

**Cheat Sheets**

- **[RMarkdown Cheatsheet](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf)**: A very reference sheet. Print this out and have above your desk when you start learning RMarkdown.
-  **[RMarkdown Reference](https://www.rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf)**: similar to the cheatsheet, but provides more detail surrounding the customisation and documents settings.

**Books:**

- **[bookdown: authoring Books and Technical Documents with R Markdown](https://bookdown.org/yihui/bookdown/)**. Essential reading for those who are considering to use the *sotonthesis* package. 
- **Dynamic Documents with R and Knitr**: a useful read for both new and advanced RMarkdown users. The first three chapters [here](https://github.com/yihui/knitr-book).
- **[Reproducible Research with R and Rstudio](https://englianhu.files.wordpress.com/2016/01/reproducible-research-with-r-and-studio-2nd-edition.pdf)**: a more general book about the techniques behind reproducible research. Although published in 2015, the book does feel a bit out of date in some areas, although largely it is an excellent resource.

**Other Presentations:**

- **[Reproducible Research](http://benmarwick.github.io/CSSS-Primer-Reproducible-Research)**: a great presentation which provides more details on the reproducible research aspects of this presentation.

## sotonthesis package

[Link to sotonthesis](https://github.com/mikey-harper/sotonthesis)

The presentation introduced the package *sotonthesis*, which is a template designed to create documents within RMarkdown in line with the University of Southampton Thesis template.

- **[sotonthesis R package](https://github.com/mikey-harper/sotonthesis)**: 
- **[sotonthesis empty template](https://github.com/mikey-harper/sotonthesis/blob/master/thesis.pdf)**: View an example of the template of the sotonthesis template.

While the template is designed to minimise edits made by the user, it is recommended that you read the **[bookdown](https://bookdown.org/yihui/bookdown/)** and have a strong understanding of RMarkdown.